
import sys

from src.space_groups import prepare_gap_env
from src.srdegrees import SR_Degrees

prepare_gap_env()


num = int(sys.argv[1])

if len(sys.argv) > 2:
    needed_mtx_fn = sys.argv[2]
    with open(needed_mtx_fn) as file:
        needed_mtx = file.read().split('\n\n')
else:
    needed_mtx = []

sr = SR_Degrees(num, dim=3, method='latex', verbose=2)
# sr.sr_degrees()

print(f"Group {num} is generated by the following elements:")
print()

print(r'$$G_{' + str(num) + r'} = \left\langle'
      + sr.display(*sr.G.G_nontriv, *sr.G._L_names, use_pref=False, sep=',')
      + r'\right\rangle$$')
print()
print()

print("Normalizer of the point group:")
norm = sr.G.point_group_normalizer()

for i in range(0, len(norm), 3):
    print(sr.display(*norm[i:i+3], sep=','))

print()

for A in sr.G.point_group_normalizer():
    if needed_mtx and str(A) not in needed_mtx:
        continue
    print('Consider matrix A=$', (sr.display(A, use_pref=False)), '$.')
    print()
    compat = sr.cocycle_compat(A)
